# Generated by Django 5.2.11 on 2026-02-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_seed_admin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('ano', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='core.categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
