# Generated by Django 5.2.11 on 2026-02-23 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
