# Generated by Django 5.2.11 on 2026-02-27 22:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_options_alter_vehiculo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(error_messages={'unique': 'Ya existe un vehículo registrado con esa placa.'}, max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('placa'), name='uniq_vehiculo_placa_ci'),
        ),
    ]
